name: Fetch market daily
on:
  schedule:
    - cron: '22 11 * * *' # UTC时间的08:30，对应中国的16:30
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        architecture: 'x64'
    - name: install requirements
      run: |
        pip install -r requirements.txt
    - name: download
      run: |
        python run.py
    - name: Create local changes
      run: |
        git add .
    - name: Commit files
      run: |
        git config --local user.email "echonoshy@gmail.com"
        git config --local user.name "Lake"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKENS }}
        branch: ${{ github.ref }}
